// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// validChars
IntegerVector validChars(std::string seq1, std::string seq2);
RcppExport SEXP alakazam_validChars(SEXP seq1SEXP, SEXP seq2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< std::string >::type seq2(seq2SEXP);
    __result = Rcpp::wrap(validChars(seq1, seq2));
    return __result;
END_RCPP
}
// seqEqual
bool seqEqual(std::string seq1, std::string seq2, CharacterVector ignore);
RcppExport SEXP alakazam_seqEqual(SEXP seq1SEXP, SEXP seq2SEXP, SEXP ignoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< std::string >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ignore(ignoreSEXP);
    __result = Rcpp::wrap(seqEqual(seq1, seq2, ignore));
    return __result;
END_RCPP
}
// pairwiseEqual
LogicalMatrix pairwiseEqual(StringVector seq);
RcppExport SEXP alakazam_pairwiseEqual(SEXP seqSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type seq(seqSEXP);
    __result = Rcpp::wrap(pairwiseEqual(seq));
    return __result;
END_RCPP
}
// seqDistRcpp
double seqDistRcpp(std::string seq1, std::string seq2, NumericMatrix dist_mat);
RcppExport SEXP alakazam_seqDistRcpp(SEXP seq1SEXP, SEXP seq2SEXP, SEXP dist_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< std::string >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    __result = Rcpp::wrap(seqDistRcpp(seq1, seq2, dist_mat));
    return __result;
END_RCPP
}
// pairwiseDistRcpp
NumericMatrix pairwiseDistRcpp(StringVector seq, NumericMatrix dist_mat);
RcppExport SEXP alakazam_pairwiseDistRcpp(SEXP seqSEXP, SEXP dist_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< StringVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_mat(dist_matSEXP);
    __result = Rcpp::wrap(pairwiseDistRcpp(seq, dist_mat));
    return __result;
END_RCPP
}
